name: ingest_v1
description: "Ingest extraction prompt pack for StoryOS"
defaults:
  temperature: 0.2
  max_output_tokens: 20000
pipelines:
  ingest_extract:
    guardrails:
      - guardrails/safety.system.md
      - guardrails/anti_hallucination.system.md
    prompts:
      system: prompts/ingest_extract.system.md
      user: prompts/ingest_extract.user.md
    schema: schemas/ingest_extract.schema.json
    output:
      format: json
